name: 'Create MySQL Container'
description: 'Create a MySQL Docker Container'
author: 'chenjunqing'
branding:
  icon: 'database'
  color: 'blue'
inputs:
  hostPort:
    description: 'The port of host'
    required: false
    default: '3306'
  containerPort:
    description: 'The port of container'
    required: false
    default: '3306'
  characterSetServer:
    description: '--character-set-server - The character set of MySQL server'
    required: false
    default: 'utf8mb4'
  collationServer:
    description: '--collation-server - The character collation of MySQL server'
    required: false
    default: 'utf8mb4_general_ci'
  mysqlVersion:
    description: 'Version of MySQL to use'
    required: false
    default: 'latest'
  mysqlRootPassword:
    description: 'MYSQL_ROOT_PASSWORD - root superuser password'
    required: false
    default: ''
  mysqlDatabase:
    description: 'MYSQL_DATABASE - name for the default database that is created'
    required: false
    default: ''
  mysqlUser:
    description: 'MYSQL_USER - create the specified user with superuser power for created database'
    required: false
    default: ''
  mysqlPassword:
    description: 'MYSQL_PASSWORD - specified superuser password which user is power for created database'
    required: false
    default: ''
  volumes:
    description: 'Volumes are the preferred mechanism for persisting data generated by and used by Docker containers'
    required: false
    default: '[]'
runs:
  using: 'docker'
  image: 'Dockerfile'
