name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Set up MySQL 8
        uses: chenjuneking/mysql-docker-action@master
        id: mysql
        with:
          mysqlVersion: 8
          mysqlDatabase: test
          mysqlRootPassword: ${{ secrets.DATABASE_PASSWORD }}
      - name: Post MySQL set up
        run: |
          echo "${{ steps.mysql.outputs.results }}"
      - name: Run test cases
        run: |
          npm install
          DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} npm test
        env:
          CI: true
